# Generated by Django 4.2.2 on 2024-07-25 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место выполнения привычки')),
                ('time', models.DateTimeField(verbose_name='время выполнения привычки')),
                ('action', models.TextField(verbose_name='действие, которое представляет собой привычка')),
                ('pleasant_habit_sign', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='переодичность')),
                ('award', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='продолжительность')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
